cargo install alacritty
cargo install bandwhich
cargo install bat
cargo install cargo-edit
cargo install cargo-expand
cargo install cargo-insta
cargo install cargo-sweep
cargo install cargo-update
cargo install cargo-watch
cargo install cobalt-bin
cargo install diesel_cli
cargo install du-dust
cargo install fd-find
cargo install flamegraph
cargo install git-delta
cargo install graphql_client_cli
cargo install grex
cargo install hyperfine
cargo install jless
cargo install just
cargo install lsd
cargo install mdbook-open-git-repo
cargo install mdcat
cargo install nu
cargo install ripgrep
cargo install sd
cargo install so
cargo install starship
cargo install tealdeer
cargo install tokei
cargo install watchexec-cli
cargo install zoxide
