cargo install cargo-xbuild
cargo install hyperfine
cargo install mdbook
cargo install bandwhich
cargo install bat
cargo install cargo-edit
cargo install cargo-sweep
cargo install cargo-update
cargo install cargo-watch
cargo install diesel_cli
cargo install du-dust
cargo install fd-find
cargo install git-delta
cargo install gitui
cargo install grex
cargo install leftwm
cargo install lsd
cargo install mdbook-open-git-repo
cargo install mdbook-open-on-gh
cargo install mdbook-toc
cargo install ripgrep
cargo install sd
cargo install starship
cargo install tokei
