#!/bin/bash
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bungcip.better-toml
code --install-extension d9705996.perl-toolbox
code --install-extension eamodio.gitlens
code --install-extension ericcirone.masontidy
code --install-extension esbenp.prettier-vscode
code --install-extension GitLab.gitlab-workflow
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-execution
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension korekontrol.saltstack
code --install-extension marp-team.marp-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension richterger.perl
code --install-extension rust-lang.rust-analyzer
code --install-extension sissel.shopify-liquid
code --install-extension skellock.just
code --install-extension usernamehw.errorlens
code --install-extension viatsko.html-mason
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhiyuan-lin.simple-perl
