font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  size: 8

hints:
  hyperlinks: true

window:
  padding:
    x: 5
    y: 5


# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x151515' # (from summerfruit-dark-256)
    foreground: '0xd0d0d0' # (from summerfruit-dark-256)
    #background: '#1d2021'
    #foreground: '#d5c4a1'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '#9a9a9a'
    #bright_foreground: '#ffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are
  # unset, the cursor color will be the inverse of the cell color.
  cursor:
    text: '#1d2021'
    cursor: '#d5c4a1'

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active. If these are unset, the
  # cursor color will be the inverse of the cell color.
  #vi_mode_cursor:
  #  text: '#000000'
  #  cursor: '#ffffff'

  # Selection colors
  #
  # Colors which should be used to draw the selection area. If selection
  # background is unset, selection color will be the inverse of the cell colors.
  # If only text is unset the cell text color will remain the same.
  #selection:
  #  text: '#eaeaea'
  #  background: '#404040'

  # Normal colors
  normal:
    black:   '#1d2021'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#d5c4a1'

  # Bright colors
  bright:
    black:   '#665c54'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#fbf1c7'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '#000000'
  #  red:     '#8c3336'
  #  green:   '#7a8530'
  #  yellow:  '#97822e'
  #  blue:    '#506d8f'
  #  magenta: '#80638e'
  #  cyan:    '#497e7a'
  #  white:   '#9a9a9a'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  indexed_colors:
    - { index: 16, color: '#fe8019' }
    - { index: 17, color: '#d65d0e' }
    - { index: 18, color: '#3c3836' }
    - { index: 19, color: '#504945' }
    - { index: 20, color: '#bdae93' }
    - { index: 21, color: '#ebdbb2' }

