[git_branch]
#symbol = " "
symbol = "⎇ "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "\\$${count}"
untracked = "?${count}"
modified = "!${count}"
deleted = "✘${count}"
staged = "+${count}"

[gcloud]
disabled = true
